### ISSUE TITLE
ContinuousTransition node does not have mean-field rules

### ISSUE THREAD

**Issue by albertpod** [ReactiveBayes/ReactiveMP.jl#401]
The current implementation of the continuous transition node allows only structured factorization between the states, i.e.,
```julia
constraints = @constraints begin
    q(x, y, h, Λ) = q(x, y)q(h)q(Λ)
end;
```

While this factorization is beneficial for state space models (as it introduces coupling between states), it doesn't allow one of $x$ or $y$ to be observed (clamped). The implementation of these (MF) rules needs to be added, which will also allow the following factorization:
```julia
constraints = @constraints begin
    q(x, y, h, Λ) = q(x)q(y)q(h)q(Λ)
end;
```

**Comment by bvdmitri** [comment]
Fixed in #406
