### ISSUE TITLE
SoftDot node does not have structured rules

### ISSUE THREAD

**Issue by albertpod** [ReactiveBayes/ReactiveMP.jl#402]
The current `SoftDot` node implementation only permits mean-field factorization between states, as shown below:
```julia
constraints = @constraints begin
  q(x, y, θ, γ) = q(x)q(y)q(θ)q(γ)
end;
```
This is likely because it was designed primarily for likelihood cases. However, including structured rules could be beneficial. This would require implementation and allow for the following factorization:
```julia
constraints = @constraints begin
  q(x, y, θ, γ) = q(x, y)q(θ)q(γ)
end;
```
Interestingly, `ReactiveMP.jl` already has this factorization and corresponding rules (just hidden :) ). `SoftDot` is essentially a univariate output of `AR` node. Since `AR` nodes (designed for state space models) copy previous states (buffering), instead of reimplementing all new structured `SoftDot` rules, one could use the `@call_rule` macro to call AR node rules and select only the first output element.

**Comment by bvdmitri** [comment]
Fixed in #404
