### ISSUE TITLE
Misleading of code in `src/approximations/linearization.jl`

### ISSUE THREAD

**Issue by Flawless1202** [ReactiveBayes/ReactiveMP.jl#415]
In the following code in `src/approximations/linearization.jl`:
https://github.com/ReactiveBayes/ReactiveMP.jl/blob/308dce4649faf8bb720e7e66750b87844b840448/src/approximations/linearization.jl#L68-L84

As far as I am concerned, the lambda function 
```Julia
(g, lx_hat) -> (ForwardDiff.gradient(splitg, lx_hat)::Vector{eltype(lx_hat)})'
```
and 
```Julia
(g, lx_hat) -> (ForwardDiff.jacobian(splitg, lx_hat)::Matrix{eltype(lx_hat)})
```
should be
```Julia
(splitg, lx_hat) -> (ForwardDiff.gradient(splitg, lx_hat)::Vector{eltype(lx_hat)})'
```
and 
```Julia
(splitg, lx_hat) -> (ForwardDiff.jacobian(splitg, lx_hat)::Matrix{eltype(lx_hat)})
```

Is it correct?

**Comment by bvdmitri** [comment]
I believe you're right here, but fortunately, later on in line 81, we pass `splitg` as the `g` argument, making it effectively equivalent. The code is indeed a bit tricky to read, but I don't anticipate it being a real bug. We can clean it up, though.

I don't quite remember the original reasoning behind using the lambda function, but it had to do with `ForwardDiff` requiring a function with a single vector argument, while we wanted to handle multi-argument functions as well."
