### ISSUE TITLE
make test breaks for Julia 1.10.7

### ISSUE THREAD

**Issue by abpolym** [ReactiveBayes/ReactiveMP.jl#433]
Running `make test` for the `lts` version of julia, i.e. `1.10.7` yields the following error:

```log
$ make test
julia -e 'import Pkg; Pkg.activate("."); Pkg.test(test_args = split("") .|> string)'
  Activating project at `~/git/ReactiveBayes/ReactiveMP.jl`
     Testing ReactiveMP
┌ Warning: Could not use exact versions of packages in manifest, re-resolving
└ @ Pkg.Operations ~/.julia/juliaup/julia-1.10.7+0.aarch64.apple.darwin14/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1822
ERROR: Unsatisfiable requirements detected for package REPL [3fa0cd96]:
 REPL [3fa0cd96] log:
 ├─possible versions are: 1.10.7 or uninstalled (package in sysimage!)                                                                                                                      └─restricted to versions 1.11.0-1 by project [349aa928] — no versions left
   └─project [349aa928] log:
     ├─possible versions are: 0.0.0 or uninstalled                                                                                                                                              └─project [349aa928] is fixed to version 0.0.0
Stacktrace
[...]
```

In Project.toml, I see that [julia 1.10 is required](https://github.com/ReactiveBayes/ReactiveMP.jl/blob/main/Project.toml#L80) but at the same time, [REPL 1.11 is required](https://github.com/ReactiveBayes/ReactiveMP.jl/blob/main/Project.toml#L69).

Should the julia requirement be pushed to 1.11 or is it the expectation that if you run julia 1.10, then you need to (somehow) have REPL 1.11 running?

`make test` runs for the current `release` version of Julia, i.e. `1.11.2`.

**Comment by bvdmitri** [comment]
I think we should downgrade minimum version for REPL to 1.10. Good catch!

**Comment by bvdmitri** [comment]
Lets see if this helps https://github.com/ReactiveBayes/ReactiveMP.jl/commit/825eba36dcaf09c9f0cfe9df3f85af2ee57dee3c

https://github.com/ReactiveBayes/ReactiveMP.jl/actions/runs/12370007652
